apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-playground
  template:
    metadata:
      labels:
        app: kube-playground
    spec:
      containers:
      - name: kube-playground-container
        image: bitnap/playground:0.0.1
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
      